export type GameSettings = {
  players: number;
  mafia: number;
  advocate?: boolean;
  amur?: boolean;
  boss?: boolean;
  detective?: boolean;
  doctor?: boolean;
  godfather?: boolean;
  hypnotizer?: boolean;
  journalist?: boolean;
  luckyGuy?: boolean;
  maniac?: boolean;
  psycho?: boolean;
  putana?: boolean;
  rat?: boolean;
  santa?: boolean;
  sheriff?: boolean;
  snitch?: boolean;
  thief?: boolean;
  widow?: boolean;
};
